spring.application.name=sprout
server.port=9000

# Database - Using the 15432 bypass for Mac/Ztunnel
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:15432/sprout?sslmode=disable}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# Hikari Tuning for Local Development
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.validation-timeout=2000
spring.datasource.hikari.initialization-fail-timeout=5000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Redis - Matching Docker Default Port
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:127.0.0.1}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=2s
spring.data.redis.repositories.enabled=true

# Kafka Common
spring.kafka.bootstrap-servers=127.0.0.1:9092
app.kafka.enabled=true
spring.kafka.listener.missing-topics-fatal=false

# Kafka Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Consumer
spring.kafka.consumer.group-id=sprout-final-test-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON Trusted Packages & Type Mapping (The Fix)
spring.kafka.consumer.properties.spring.json.trusted.packages=com.avijeet.sprout.*
# This ensures Kafka knows how to rebuild your DTO
spring.kafka.consumer.properties.spring.json.value.default.type=com.avijeet.sprout.dto.OrderNotificationEvent

app.kafka.bulk-group=sprout-bulk-processor-group
spring.kafka.producer.properties.max.request.size=5242880
spring.kafka.consumer.properties.max.partition.fetch.bytes=5242880

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true

# Elasticsearch Configuration
spring.elasticsearch.socket-timeout=30s
spring.elasticsearch.uris=http://localhost:9200
spring.data.elasticsearch.repositories.enabled=true
spring.data.elasticsearch.reactive.repositories.enabled=false
management.health.elasticsearch.enabled=false
