spring.application.name=sprout
server.port=9000

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:15432/sprout?sslmode=disable}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.hikari.connection-timeout=${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:5000}
spring.datasource.hikari.validation-timeout=${SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT:2000}
spring.datasource.hikari.initialization-fail-timeout=${SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT:5000}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.open-in-view=false

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:127.0.0.1}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:16379}
spring.data.redis.timeout=${SPRING_DATA_REDIS_TIMEOUT:2s}
spring.data.redis.repositories.enabled=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:19092}
spring.kafka.listener.missing-topics-fatal=false