spring.application.name=sprout
server.port=9000

## Spring data jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/sprout
spring.jpa.hibernate.ddl-auto=update
spring.datasource.password=postgres
spring.datasource.username=postgres
spring.jpa.show-sql=true